import React, { useState, useEffect } from 'react';
import { useQuery, keepPreviousData } from '@tanstack/react-query';

export default function ReportsTable({ type }) {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');
  const [dateFilter, setDateFilter] = useState('all');
  const title = type === 'inventory' ? 'Inventory Reports' : 'Incident Reports';

  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(search);
      setPage(1); // Reset page on new search
    }, 500);
    return () => clearTimeout(timer);
  }, [search]);

  // Reset page when date filter changes
  useEffect(() => {
    setPage(1);
  }, [dateFilter]);

  const { data, isLoading, isFetching, error } = useQuery({
    queryKey: ['reports', type, page, debouncedSearch, dateFilter],
    queryFn: async () => {
      const res = await fetch(`/api/reports?type=${type}&page=${page}&search=${encodeURIComponent(debouncedSearch)}&date_filter=${dateFilter}`, {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('admin_token')}`
        }
      });
      if (!res.ok) throw new Error('Failed to fetch reports');
      return res.json();
    },
    placeholderData: keepPreviousData
  });

  const reports = data?.data || [];

  if (isLoading) {
    return (
      <div className="flex justify-center items-center p-12">
        <div className="w-8 h-8 border-4 border-[#0a84ff]/30 border-t-[#0a84ff] rounded-full animate-spin"></div>
        <span className="ml-3 text-gray-400 font-medium">Loading {title}...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8 text-center text-[#ef4444] bg-[#ef4444]/10 rounded-xl">
        Error loading reports: {error.message}
      </div>
    );
  }

  return (
    <div className="bg-[#111116] border border-[#1f1f26] rounded-2xl p-6 shadow-xl">
      <div className="flex flex-col md:flex-row justify-between md:items-center gap-4 mb-6">
        <div className="flex items-center gap-3">
            <h2 className="text-xl font-bold text-white m-0">{title}</h2>
            {isFetching && !isLoading && (
                <div className="w-5 h-5 border-2 border-[#0a84ff]/30 border-t-[#0a84ff] rounded-full animate-spin"></div>
            )}
        </div>
        <div className="flex flex-col sm:flex-row gap-3">
          <input 
            type="text" 
            placeholder="Search by title or name..." 
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="bg-[#181822] border border-[#2b2b35] text-white px-4 py-2 rounded-lg focus:outline-none focus:border-[#0a84ff] transition-colors text-sm w-full sm:w-64"
          />
          <select 
            value={dateFilter}
            onChange={(e) => setDateFilter(e.target.value)}
            className="bg-[#181822] border border-[#2b2b35] text-white px-4 py-2 rounded-lg focus:outline-none focus:border-[#0a84ff] transition-colors text-sm cursor-pointer"
          >
            <option value="all">All Time</option>
            <option value="today">Today</option>
            <option value="this_week">This Week</option>
            <option value="this_month">This Month</option>
            <option value="this_year">This Year</option>
          </select>
        </div>
      </div>

      {reports.length === 0 ? (
        <div className="p-12 text-center bg-[#181822] border border-[#2b2b35] rounded-xl text-gray-400 font-medium">
          No {type} reports generated yet.
        </div>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-[#181822]">
                <th className="p-4 text-gray-400 font-semibold text-sm border-b border-[#2b2b35] rounded-tl-lg">Report Title</th>
                <th className="p-4 text-gray-400 font-semibold text-sm border-b border-[#2b2b35]">Generated By</th>
                <th className="p-4 text-gray-400 font-semibold text-sm border-b border-[#2b2b35]">Date / Time</th>
                <th className="p-4 text-gray-400 font-semibold text-sm border-b border-[#2b2b35] rounded-tr-lg">Action</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report) => (
                <tr key={report.id} className="hover:bg-[rgba(255,255,255,0.02)] transition-colors border-b border-[#1f1f26]">
                  <td className="p-4">
                    <div className="flex items-center gap-3">
                      <div className="bg-[#0a84ff]/10 text-[#0a84ff] w-8 h-8 rounded flex items-center justify-center font-bold">
                        📄
                      </div>
                      <div>
                        <div className="text-white font-medium text-sm">{report.title}</div>
                        <div className="text-gray-500 text-xs">PDF Document</div>
                      </div>
                    </div>
                  </td>
                  <td className="p-4 text-gray-300 text-sm">
                    {report.generated_by}
                  </td>
                  <td className="p-4 text-gray-400 text-sm">
                    {new Date(report.date_generated).toLocaleString(undefined, { 
                      month: 'short', day: 'numeric', year: 'numeric', 
                      hour: '2-digit', minute: '2-digit' 
                    })}
                  </td>
                  <td className="p-4">
                    <a 
                      href={report.file_url} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-2 bg-[#0a84ff]/10 hover:bg-[#0a84ff]/20 text-[#0a84ff] border border-[#0a84ff]/30 px-4 py-2 rounded-lg text-xs font-bold transition-all"
                    >
                      <span>👁️</span> View PDF
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Pagination */}
      {data?.last_page > 1 && (
        <div className="flex justify-between items-center mt-6 p-4 bg-[#181822] border border-[#2b2b35] rounded-xl">
          <span className="text-gray-400 text-xs font-medium">
            Showing page {data.current_page} of {data.last_page} ({data.total} total)
          </span>
          <div className="flex gap-2">
            <button 
              disabled={data.current_page === 1}
              onClick={() => setPage(p => Math.max(1, p - 1))}
              className={`px-4 py-2 bg-[#0c0c10] border border-[#2b2b35] rounded-lg text-white text-xs font-semibold ${data.current_page > 1 ? 'hover:bg-[#1f1f26] cursor-pointer' : 'opacity-50 cursor-not-allowed'}`}
            >
              Previous
            </button>
            <button 
              disabled={data.current_page >= data.last_page}
              onClick={() => setPage(p => p + 1)}
              className={`px-4 py-2 bg-[#0c0c10] border border-[#2b2b35] rounded-lg text-white text-xs font-semibold ${data.current_page < data.last_page ? 'hover:bg-[#1f1f26] cursor-pointer' : 'opacity-50 cursor-not-allowed'}`}
            >
              Next
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
