import React, { useState, useEffect } from 'react';
import { io } from 'socket.io-client';
import { useQueryClient } from '@tanstack/react-query';
import AdminNavbar from './Admin/AdminNavbar';
import UserManagement from './Admin/UserManagement';
import RespondersManager from './Staff1/RespondersManager';
import EventsManager from './Staff1/EventsManager';
import AdminDashboard from './Admin/AdminDashboard';

export default function AdminApp() {
    const [token, setToken] = useState(localStorage.getItem('admin_token') || null);
    const [adminUser, setAdminUser] = useState(null);
    const queryClient = useQueryClient();
    const [activeSection, setActiveSection] = useState('dashboard');

    // Global Notifications
    const [notifications, setNotifications] = useState([]);
    const [showNotificationModal, setShowNotificationModal] = useState(false);
    const [currentNotification, setCurrentNotification] = useState(null);
    const [showNotificationsMenu, setShowNotificationsMenu] = useState(false);
    const [pdfPreviewUrl, setPdfPreviewUrl] = useState(null);

    // Fetch notifications and listen to socket for updates
    useEffect(() => {
        const fetchNotifications = async () => {
            try {
                const res = await fetch('/api/notifications');
                const data = await res.json();
                setNotifications(data);

                const readIds = JSON.parse(localStorage.getItem('readNotifications') || '[]');
                const unreadAlerts = data.filter(n => n.type === 'event_alert' && !readIds.includes(n.id));
                
                if (unreadAlerts.length > 0) {
                    setCurrentNotification(unreadAlerts[0]);
                    setShowNotificationModal(true);
                }
            } catch (err) {
                console.error('Failed to fetch notifications', err);
            }
        };
        
        fetchNotifications();
        
        const socket = io(`http://${window.location.hostname}:3000`);
        socket.on('new_notification', fetchNotifications);
        socket.on('incoming_emergency_call', fetchNotifications);

        return () => {
            socket.disconnect();
        };
    }, []);

    const dismissNotification = () => {
        if (currentNotification) {
            const readIds = JSON.parse(localStorage.getItem('readNotifications') || '[]');
            if (!readIds.includes(currentNotification.id)) {
                readIds.push(currentNotification.id);
                localStorage.setItem('readNotifications', JSON.stringify(readIds));
            }
        }
        setShowNotificationModal(false);
        setCurrentNotification(null);
    };

    const generatePDFReport = (n) => {
        const element = document.createElement('div');
        element.innerHTML = `
            <div style="padding: 40px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; max-width: 800px; margin: 0 auto;">
                <h2 style="text-align: center; color: #111; margin-bottom: 5px;">INVENTORY SUBMISSION REPORT</h2>
                <p style="text-align: center; color: #666; margin-top: 0;">MDRRMO Management System</p>
                <hr style="border: 1px solid #ddd; margin: 20px 0;" />
                <p><strong>Submitted on:</strong> ${new Date(n.created_at).toLocaleString()}</p>
                <div style="margin-top: 30px; font-size: 14px; line-height: 1.6; white-space: pre-wrap; padding: 20px; background: #f9f9f9; border-radius: 8px; border: 1px solid #eee;">
                    ${n.message}
                </div>
                <hr style="border: 1px solid #ddd; margin-top: 50px; margin-bottom: 20px;" />
                <p style="text-align: center; font-size: 10px; color: #777;">Auto-generated by Admin Control Center</p>
            </div>
        `;
        
        const opt = {
            margin:       0.5,
            filename:     `inventory_report_submission_${new Date(n.created_at).toISOString().split('T')[0]}.pdf`,
            image:        { type: 'jpeg', quality: 0.98 },
            html2canvas:  { scale: 2 },
            jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
        };

        if (window.html2pdf) {
            window.html2pdf().set(opt).from(element).outputPdf('datauristring').then(function(pdfAsString) {
                setPdfPreviewUrl(pdfAsString);
            });
        } else {
            console.error('html2pdf is not loaded');
            alert('Failed to generate PDF. Tool is missing.');
        }
    };

    const handleNotificationClick = (n) => {
        const readIds = JSON.parse(localStorage.getItem('readNotifications') || '[]');
        if (!readIds.includes(n.id)) {
            readIds.push(n.id);
            localStorage.setItem('readNotifications', JSON.stringify(readIds));
        }

        if (n.title === 'Inventory Report Submission') {
            generatePDFReport(n);
        } else {
            setCurrentNotification(n);
            setShowNotificationModal(true);
        }
        setShowNotificationsMenu(false);
    };

    // Login Form State
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [loginLoading, setLoginLoading] = useState(false);
    const [loginError, setLoginError] = useState(null);

    // On Load: fetch profile if token exists
    useEffect(() => {
        if (token) {
            fetchAdminProfile();
        }
    }, [token]);

    const fetchAdminProfile = async () => {
        try {
            const res = await fetch('/api/user', {
                headers: {
                    'Accept': 'application/json',
                    'Authorization': `Bearer ${token}`
                }
            });
            if (res.ok) {
                const data = await res.json();
                setAdminUser(data);
            }
        } catch (e) {
            console.error('Failed to load profile', e);
        }
    };

    const handleLogin = async (e) => {
        e.preventDefault();
        setLoginLoading(true);
        setLoginError(null);

        try {
            const res = await fetch('/api/login', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json'
                },
                body: JSON.stringify({ email, password })
            });

            const data = await res.json();

            if (!res.ok) {
                throw new Error(data.message || 'Login failed. Please check credentials.');
            }

            if (data.user.role !== 'admin') {
                throw new Error('Access denied. Admin privileges required.');
            }

            localStorage.setItem('admin_token', data.access_token);
            setToken(data.access_token);
            setAdminUser(data.user);
        } catch (e) {
            setLoginError(e.message);
        } finally {
            setLoginLoading(false);
        }
    };

    const handleLogout = () => {
        localStorage.removeItem('admin_token');
        setToken(null);
        setAdminUser(null);
        queryClient.clear();
    };

    // Render Login Interface if no token
    if (!token) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-[#08080a] px-4 font-sans">
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(10,132,255,0.08),transparent_50%)] pointer-events-none" />
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_bottom_left,rgba(99,102,241,0.05),transparent_40%)] pointer-events-none" />
                
                <div className="w-full max-w-md bg-[#111115] border border-[#23232a] rounded-3xl p-8 shadow-2xl relative z-10">
                    <div className="flex justify-center mb-6">
                        <div className="bg-[#181822] p-4 rounded-2xl border border-[#2b2b35]">
                            <img src="/images/mdrrmo_logo.png" alt="MDRRMO Logo" className="w-16 h-16 object-contain" />
                        </div>
                    </div>

                    <h2 className="text-2xl font-extrabold text-center text-white tracking-tight mb-1">EMERGENCY RESPONDER</h2>
                    <p className="text-sm text-gray-400 text-center mb-8">Admin Control Center</p>

                    {loginError && (
                        <div className="mb-6 bg-red-950/40 border border-red-500/50 rounded-xl p-4 text-sm text-red-400 text-center animate-pulse">
                            {loginError}
                        </div>
                    )}

                    <form onSubmit={handleLogin} className="space-y-6">
                        <div>
                            <label className="block text-xs font-semibold text-gray-300 uppercase tracking-wider mb-2">Email Address</label>
                            <input
                                type="email"
                                required
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                className="w-full bg-[#181820] border border-[#2b2b35] rounded-xl px-4 py-3.5 text-sm text-white focus:outline-none focus:border-[#0a84ff] transition-all"
                                placeholder="admin@mdrrmo.com"
                            />
                        </div>

                        <div>
                            <label className="block text-xs font-semibold text-gray-300 uppercase tracking-wider mb-2">Password</label>
                            <input
                                type="password"
                                required
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                className="w-full bg-[#181820] border border-[#2b2b35] rounded-xl px-4 py-3.5 text-sm text-white focus:outline-none focus:border-[#0a84ff] transition-all"
                                placeholder="••••••••"
                            />
                        </div>

                        <button
                            type="submit"
                            disabled={loginLoading}
                            className="w-full bg-[#0a84ff] hover:bg-[#0070df] text-white font-bold py-3.5 px-4 rounded-xl transition-all shadow-lg hover:shadow-[#0a84ff]/20 flex items-center justify-center gap-2 cursor-pointer disabled:opacity-75"
                        >
                            {loginLoading ? (
                                <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                            ) : (
                                'Access Dashboard'
                            )}
                        </button>
                    </form>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-[#08080a] text-gray-100 font-sans pb-12">
            {/* Header banner glow */}
            <div className="absolute top-0 left-0 right-0 h-96 bg-[radial-gradient(circle_at_top,rgba(10,132,255,0.08),transparent_70%)] pointer-events-none" />

            {/* Navbar */}
            <AdminNavbar 
                adminUser={adminUser} 
                notifications={notifications} 
                showNotificationsMenu={showNotificationsMenu}
                setShowNotificationsMenu={setShowNotificationsMenu}
                handleLogout={handleLogout} 
                onNotificationClick={handleNotificationClick}
            />

            {/* Admin Tabs */}
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-6 mb-4 relative z-10 overflow-x-auto custom-scrollbar pb-2">
                <div className="flex space-x-2 p-1 bg-[#111116] border border-[#1f1f26] rounded-xl w-fit min-w-max">
                    <button
                        onClick={() => setActiveSection('dashboard')}
                        className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${
                            activeSection === 'dashboard' 
                                ? 'bg-gradient-to-r from-[#0a84ff] to-[#005bb5] text-white shadow-lg shadow-[#0a84ff]/20' 
                                : 'text-gray-400 hover:text-white hover:bg-[#181822]'
                        }`}
                    >
                        Overview Dashboard
                    </button>
                    <button
                        onClick={() => setActiveSection('users')}
                        className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${
                            activeSection === 'users' 
                                ? 'bg-gradient-to-r from-[#0a84ff] to-[#005bb5] text-white shadow-lg shadow-[#0a84ff]/20' 
                                : 'text-gray-400 hover:text-white hover:bg-[#181822]'
                        }`}
                    >
                        User Management
                    </button>
                    <button
                        onClick={() => setActiveSection('personnel')}
                        className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${
                            activeSection === 'personnel' 
                                ? 'bg-gradient-to-r from-[#0a84ff] to-[#005bb5] text-white shadow-lg shadow-[#0a84ff]/20' 
                                : 'text-gray-400 hover:text-white hover:bg-[#181822]'
                        }`}
                    >
                        Personnel Availability
                    </button>
                    <button
                        onClick={() => setActiveSection('events')}
                        className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${
                            activeSection === 'events' 
                                ? 'bg-gradient-to-r from-[#0a84ff] to-[#005bb5] text-white shadow-lg shadow-[#0a84ff]/20' 
                                : 'text-gray-400 hover:text-white hover:bg-[#181822]'
                        }`}
                    >
                        Events
                    </button>
                </div>
            </div>

            <div className="relative z-10">
                {activeSection === 'dashboard' && <AdminDashboard setActiveSection={setActiveSection} />}
                {activeSection === 'users' && <UserManagement token={token} handleLogout={handleLogout} />}
                {activeSection === 'personnel' && (
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="bg-[#111115] border border-[#1f1f26] rounded-2xl overflow-hidden p-6 mt-2 shadow-2xl">
                            <RespondersManager />
                        </div>
                    </div>
                )}
                {activeSection === 'events' && (
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="mt-2">
                            <EventsManager role="Admin" />
                        </div>
                    </div>
                )}
            </div>

            {/* Global Notification Modal */}
            {showNotificationModal && currentNotification && (
                <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-[1000] p-4">
                    <div className="bg-[#1e212b] border-2 border-red-500 rounded-xl w-full max-w-md shadow-[0_10px_40px_rgba(239,68,68,0.2)] animate-[popIn_0.3s_cubic-bezier(0.175,0.885,0.32,1.275)]">
                        <div className="flex justify-between items-center p-5 border-b border-[#2d3748] bg-red-500/10 rounded-t-lg">
                            <h3 className="m-0 text-red-500 text-lg font-bold">🚨 New System Alert</h3>
                            <button onClick={dismissNotification} className="text-gray-400 hover:text-white transition-colors cursor-pointer text-xl">✖</button>
                        </div>
                        <div className="p-6">
                            <h4 className="m-0 mb-2.5 text-white text-base font-semibold">{currentNotification.title}</h4>
                            {currentNotification.title === 'Inventory Report Submission' ? (
                                <p className="m-0 text-slate-300 text-sm leading-relaxed">
                                    An inventory report has been submitted by Staff. You can download and view the details in PDF format.
                                </p>
                            ) : (
                                <p className="m-0 text-slate-300 text-sm leading-relaxed">{currentNotification.message}</p>
                            )}
                        </div>
                        <div className="p-5 border-t border-[#2d3748]">
                            {currentNotification.title === 'Inventory Report Submission' ? (
                                <button onClick={() => { generatePDFReport(currentNotification); dismissNotification(); }} className="w-full bg-[#e11d48] hover:bg-[#be123c] text-white font-bold py-3 px-4 rounded-xl transition-all shadow-lg cursor-pointer">
                                    📄 View PDF Report
                                </button>
                            ) : (
                                <button onClick={dismissNotification} className="w-full bg-[#0a84ff] hover:bg-[#0070df] text-white font-bold py-3 px-4 rounded-xl transition-all shadow-lg cursor-pointer">
                                    Acknowledge
                                </button>
                            )}
                        </div>
                    </div>
                    <style>{`
                        @keyframes popIn {
                            0% { transform: scale(0.8); opacity: 0; }
                            100% { transform: scale(1); opacity: 1; }
                        }
                    `}</style>
                </div>
            )}

            {/* PDF Viewer Modal */}
            {pdfPreviewUrl && (
                <div className="fixed inset-0 bg-black/90 flex flex-col items-center justify-center z-[2000] p-4">
                    <div className="w-full max-w-4xl h-[85vh] bg-white rounded-xl overflow-hidden flex flex-col shadow-2xl animate-[popIn_0.3s_cubic-bezier(0.175,0.885,0.32,1.275)]">
                        <div className="bg-[#181822] border-b border-[#2b2b35] p-4 flex justify-between items-center">
                            <h3 className="text-white font-bold text-lg m-0 flex items-center gap-2">
                                <span>📄</span> Inventory Report Viewer
                            </h3>
                            <button onClick={() => setPdfPreviewUrl(null)} className="bg-red-500 hover:bg-red-600 text-white px-4 py-1.5 rounded-lg font-bold text-sm transition-colors cursor-pointer">
                                Close Viewer
                            </button>
                        </div>
                        <iframe 
                            src={pdfPreviewUrl} 
                            title="PDF Preview"
                            className="w-full flex-1 border-0 bg-white"
                        />
                    </div>
                </div>
            )}
        </div>
    );
}
