<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;

class ReportController extends Controller
{
    /**
     * Retrieve list of reports from the filesystem based on type
     */
    public function index(Request $request)
    {
        $type = $request->query('type', 'inventory'); // 'inventory' or 'incident'
        
        $directory = 'reports/' . $type;
        $files = Storage::disk('public')->files($directory);

        $reports = [];

        foreach ($files as $file) {
            $filename = basename($file);
            
            // Expected filename format: Type_Timestamp_GeneratedBy_Random.pdf
            // E.g., InventoryReport_1681234567_John_Doe_abcd.pdf
            $parts = explode('_', pathinfo($filename, PATHINFO_FILENAME));
            
            if (count($parts) >= 3) {
                $reportTitle = $parts[0];
                $timestamp = (int)$parts[1];
                
                // Extract generated by (reconstruct name if there are multiple parts)
                $generatedByParts = array_slice($parts, 2, -1);
                $generatedBy = count($generatedByParts) > 0 ? implode(' ', $generatedByParts) : 'System';
                
                $dateGenerated = date('c', $timestamp);
            } else {
                // Fallback if filename doesn't match standard pattern
                $reportTitle = ucfirst($type) . ' Report';
                $timestamp = Storage::disk('public')->lastModified($file);
                $dateGenerated = date('c', $timestamp);
                $generatedBy = 'Unknown User';
            }

            $reports[] = [
                'id' => $filename,
                'title' => preg_replace('/(?<!^)([A-Z])/', ' $1', $reportTitle),
                'type' => $type,
                'generated_by' => str_replace('-', ' ', $generatedBy),
                'date_generated' => $dateGenerated,
                'timestamp' => $timestamp,
                'file_url' => asset('storage/' . $file)
            ];
        }

        $search = strtolower($request->query('search', ''));
        $dateFilter = $request->query('date_filter', 'all');

        $filteredReports = [];
        foreach ($reports as $report) {
            $matchSearch = true;
            if ($search !== '') {
                // "concat search" equivalent in PHP: search across title and generated_by
                $concatText = strtolower($report['title'] . ' ' . $report['generated_by']);
                if (strpos($concatText, $search) === false) {
                    $matchSearch = false;
                }
            }

            $matchDate = true;
            if ($dateFilter !== 'all') {
                $reportTime = $report['timestamp'];
                $now = time();
                if ($dateFilter === 'today') {
                    if (date('Y-m-d', $reportTime) !== date('Y-m-d', $now)) $matchDate = false;
                } elseif ($dateFilter === 'this_week') {
                    if (date('W Y', $reportTime) !== date('W Y', $now)) $matchDate = false;
                } elseif ($dateFilter === 'this_month') {
                    if (date('Y-m', $reportTime) !== date('Y-m', $now)) $matchDate = false;
                } elseif ($dateFilter === 'this_year') {
                    if (date('Y', $reportTime) !== date('Y', $now)) $matchDate = false;
                }
            }

            if ($matchSearch && $matchDate) {
                $filteredReports[] = $report;
            }
        }

        // Sort by timestamp descending (newest first)
        usort($filteredReports, function ($a, $b) {
            return $b['timestamp'] <=> $a['timestamp'];
        });

        // Simple manual pagination
        $page = (int)$request->query('page', 1);
        $perPage = 10;
        $total = count($filteredReports);
        $totalPages = ceil($total / $perPage);
        $offset = ($page - 1) * $perPage;
        
        $paginatedReports = array_slice($filteredReports, $offset, $perPage);

        return response()->json([
            'data' => $paginatedReports,
            'current_page' => $page,
            'last_page' => max(1, $totalPages),
            'total' => $total,
            'per_page' => $perPage
        ]);
    }

    /**
     * Upload and save a new report PDF to the filesystem
     */
    public function store(Request $request)
    {
        $request->validate([
            'file' => 'required|file|mimes:pdf',
            'type' => 'required|string|in:inventory,incident',
            'title' => 'required|string',
            'generated_by' => 'required|string'
        ]);

        $type = $request->type;
        $title = str_replace(' ', '', $request->title);
        $generatedBy = str_replace(' ', '-', $request->generated_by);
        $timestamp = time();
        $random = substr(md5(mt_rand()), 0, 5);

        // Build structured filename
        $filename = "{$title}_{$timestamp}_{$generatedBy}_{$random}.pdf";
        
        // Save file to storage/app/public/reports/{type}
        $path = $request->file('file')->storeAs('reports/' . $type, $filename, 'public');

        try {
            \Illuminate\Support\Facades\Http::timeout(3)->post('http://localhost:3000/api/new-notification', []);
        } catch (\Exception $e) {
            // Ignore if node server is down
        }

        return response()->json([
            'success' => true,
            'message' => 'Report saved successfully',
            'file_url' => asset('storage/' . $path)
        ], 201);
    }
}

